- Apps:
    - FinTrack:
        icon: /icons/fintrack.svg
        href: "http://100.69.168.92:8080"
        description: "My personal finance app"
        server: my-docker
        container: fintrack-frontend

    - Noter:
        icon: /icons/noter.svg
        href: "http://100.69.168.92:8081"
        description: "Noter web interface"
        server: my-docker
        container: noter-frontend

    - File Browser:
        icon: filebrowser
        href: "http://100.69.168.92:8083"
        description: "Simple web-based file manager"
        server: my-docker
        container: filebrowser

- Others:
    - Vaultwarden:
        icon: bitwarden
        href: "https://100.69.168.92"
        description: "Password manager"
        server: my-docker
        container: vaultwarden

    - Immich:
        icon: immich
        href: "http://100.69.168.92:2283"
        description: "Photos & video backup"
        server: my-docker
        container: immich_server

    - Jellyfin:
        icon: jellyfin.png
        href: "http://100.69.168.92:8096"
        description: Media Server

    - Portainer:
        icon: portainer
        href: "http://100.69.168.92:9000"
        description: "Docker management"
        server: my-docker
        container: portainer

    - Dozzle:
        icon: dozzle
        href: "http://100.69.168.92:8085"
        description: "Real-time Docker log viewer"
        server: my-docker
        container: dozzle

    - Uptime Kuma:
        icon: uptime-kuma
        href: "http://100.69.168.92:3001"
        description: "Status & uptime monitoring"
        server: my-docker
        container: uptime-kuma

    - AdGuard Home:
        icon: adguard-home
        href: "http://100.69.168.92:8086"
        description: "Network-wide ad blocker"
        server: my-docker
        container: adguardhome

    - n8n:
        icon: n8n
        href: "http://100.69.168.92:5678"
        description: "Workflow automation"
        server: my-docker
        container: n8n