- search:
    provider: google
    target: _blank
    focus: true
    showInHeader: true

- resources:
    cpu: true
    memory: true
    disk: /
    expanded: true

- datetime:
    text_size: md
    format:
      timeStyle: short
      dateStyle: medium

- openmeteo:
    label: Enschede
    latitude: 52.2215
    longitude: 6.8937
    units: metric